
package com.danskebank.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:31.872+02:00
 * Generated source version: 3.1.3
 * 
 */
public final class CancelV02_CancelV02_Client {

    private static final QName SERVICE_NAME = new QName("http://www.danskebank.com/services/", "CancelV02Interface");

    private CancelV02_CancelV02_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CancelV02Interface.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CancelV02Interface ss = new CancelV02Interface(wsdlURL, SERVICE_NAME);
        CancelV02 port = ss.getCancelV02();  
        
        {
        System.out.println("Invoking cancel...");
        com.danskebank.services.CancelInput _cancel_input = new com.danskebank.services.CancelInput();
        _cancel_input.setDateFrom("DateFrom204885323");
        _cancel_input.setDateTo("DateTo455015488");
        _cancel_input.setMerchantID("MerchantID1870933101");
        _cancel_input.setOrderID("OrderID-54303314");
        _cancel_input.setCustomerId("CustomerId1619044728");
        _cancel_input.setTest("Test887058947");
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType _cancel_securityVal = new org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType();
        java.util.List<java.lang.Object> _cancel_securityValAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _cancel_securityValAnyVal1 = null;
        _cancel_securityValAny.add(_cancel_securityValAnyVal1);
        _cancel_securityVal.getAny().addAll(_cancel_securityValAny);
        javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> _cancel_security = new javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType>(_cancel_securityVal);
        com.danskebank.securesoapsgw.RequestHeaderType _cancel_requestHeader = new com.danskebank.securesoapsgw.RequestHeaderType();
        _cancel_requestHeader.setSenderId("SenderId283469478");
        _cancel_requestHeader.setSignerId1("SignerId1-1149254912");
        _cancel_requestHeader.setSignerId2("SignerId21451337113");
        _cancel_requestHeader.setSignerId3("SignerId31663364420");
        _cancel_requestHeader.setDBCryptId("DBCryptId626168642");
        _cancel_requestHeader.setRequestId("RequestId2122467863");
        _cancel_requestHeader.setTimestamp("Timestamp-1641185139");
        _cancel_requestHeader.setLanguage("Language-2097152666");
        com.danskebank.services.CancelOutput _cancel__return = port.cancel(_cancel_input, _cancel_security, _cancel_requestHeader);
        System.out.println("cancel.result=" + _cancel__return);

        System.out.println("cancel._cancel_security=" + _cancel_security.value);

        }

        System.exit(0);
    }

}
