package com.danskebank.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:31.943+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "CancelV02Interface", 
                  wsdlLocation = "CancelV02.wsdl",
                  targetNamespace = "http://www.danskebank.com/services/") 
public class CancelV02Interface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.danskebank.com/services/", "CancelV02Interface");
    public final static QName CancelV02 = new QName("http://www.danskebank.com/services/", "CancelV02");
    static {
        URL url = CancelV02Interface.class.getResource("CancelV02.wsdl");
        if (url == null) {
            url = CancelV02Interface.class.getClassLoader().getResource("CancelV02.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CancelV02Interface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CancelV02.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CancelV02Interface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CancelV02Interface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelV02Interface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CancelV02Interface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CancelV02Interface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CancelV02Interface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CancelV02
     */
    @WebEndpoint(name = "CancelV02")
    public CancelV02 getCancelV02() {
        return super.getPort(CancelV02, CancelV02.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelV02
     */
    @WebEndpoint(name = "CancelV02")
    public CancelV02 getCancelV02(WebServiceFeature... features) {
        return super.getPort(CancelV02, CancelV02.class, features);
    }

}
