
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.danskebank.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:31.929+02:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CancelV02Interface",
                      portName = "CancelV02",
                      targetNamespace = "http://www.danskebank.com/services/",
                      wsdlLocation = "CancelV02.wsdl",
                      endpointInterface = "com.danskebank.services.CancelV02")
                      
public class CancelV02Impl implements CancelV02 {

    private static final Logger LOG = Logger.getLogger(CancelV02Impl.class.getName());

    /* (non-Javadoc)
     * @see com.danskebank.services.CancelV02#cancel(com.danskebank.services.CancelInput  input ,)org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType  security ,)com.danskebank.securesoapsgw.RequestHeaderType  requestHeader )*
     */
    public com.danskebank.services.CancelOutput cancel(com.danskebank.services.CancelInput input,javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> security,com.danskebank.securesoapsgw.RequestHeaderType requestHeader) { 
        LOG.info("Executing operation cancel");
        System.out.println(input);
        System.out.println(security.value);
        System.out.println(requestHeader);
        try {
            com.danskebank.services.CancelOutput _return = new com.danskebank.services.CancelOutput();
            _return.setReturnCode("ReturnCode1021558834");
            _return.setReasonCode("ReasonCode741811244");
            _return.setOriginalTransactionId("OriginalTransactionId1931402327");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
