
package com.danskebank.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:34.827+02:00
 * Generated source version: 3.1.3
 * 
 */
public final class CaptureV02_CaptureV02_Client {

    private static final QName SERVICE_NAME = new QName("http://www.danskebank.com/services/", "CaptureV02Interface");

    private CaptureV02_CaptureV02_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CaptureV02Interface.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CaptureV02Interface ss = new CaptureV02Interface(wsdlURL, SERVICE_NAME);
        CaptureV02 port = ss.getCaptureV02();  
        
        {
        System.out.println("Invoking capture...");
        com.danskebank.services.CaptureInput _capture_input = new com.danskebank.services.CaptureInput();
        _capture_input.setBulkRef("BulkRef120653988");
        _capture_input.setDateFrom("DateFrom-1226601390");
        _capture_input.setDateTo("DateTo1366532645");
        _capture_input.setAmount(new java.math.BigDecimal("8193562900887591583.2754927406543737309"));
        _capture_input.setMerchantId("MerchantId-314351184");
        _capture_input.setOrderId("OrderId-1242551690");
        _capture_input.setTest("Test-1023318064");
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType _capture_securityVal = new org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType();
        java.util.List<java.lang.Object> _capture_securityValAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _capture_securityValAnyVal1 = null;
        _capture_securityValAny.add(_capture_securityValAnyVal1);
        _capture_securityVal.getAny().addAll(_capture_securityValAny);
        javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> _capture_security = new javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType>(_capture_securityVal);
        com.danskebank.securesoapsgw.RequestHeaderType _capture_requestHeader = new com.danskebank.securesoapsgw.RequestHeaderType();
        _capture_requestHeader.setSenderId("SenderId407316502");
        _capture_requestHeader.setSignerId1("SignerId11318061406");
        _capture_requestHeader.setSignerId2("SignerId22072609065");
        _capture_requestHeader.setSignerId3("SignerId3176542504");
        _capture_requestHeader.setDBCryptId("DBCryptId-1888148574");
        _capture_requestHeader.setRequestId("RequestId1834743638");
        _capture_requestHeader.setTimestamp("Timestamp219670011");
        _capture_requestHeader.setLanguage("Language-1612017094");
        com.danskebank.services.CaptureOutput _capture__return = port.capture(_capture_input, _capture_security, _capture_requestHeader);
        System.out.println("capture.result=" + _capture__return);

        System.out.println("capture._capture_security=" + _capture_security.value);

        }

        System.exit(0);
    }

}
