package com.danskebank.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:34.888+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "CaptureV02Interface", 
                  wsdlLocation = "CaptureV02.wsdl",
                  targetNamespace = "http://www.danskebank.com/services/") 
public class CaptureV02Interface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.danskebank.com/services/", "CaptureV02Interface");
    public final static QName CaptureV02 = new QName("http://www.danskebank.com/services/", "CaptureV02");
    static {
        URL url = CaptureV02Interface.class.getResource("CaptureV02.wsdl");
        if (url == null) {
            url = CaptureV02Interface.class.getClassLoader().getResource("CaptureV02.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CaptureV02Interface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "CaptureV02.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CaptureV02Interface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaptureV02Interface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaptureV02Interface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CaptureV02Interface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CaptureV02Interface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CaptureV02Interface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CaptureV02
     */
    @WebEndpoint(name = "CaptureV02")
    public CaptureV02 getCaptureV02() {
        return super.getPort(CaptureV02, CaptureV02.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaptureV02
     */
    @WebEndpoint(name = "CaptureV02")
    public CaptureV02 getCaptureV02(WebServiceFeature... features) {
        return super.getPort(CaptureV02, CaptureV02.class, features);
    }

}
