
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.danskebank.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:37.856+02:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "GetReservationsV02Interface",
                      portName = "GetReservationsV02",
                      targetNamespace = "http://www.danskebank.com/services/",
                      wsdlLocation = "GetReservationsV02.wsdl",
                      endpointInterface = "com.danskebank.services.GetReservationsV02")
                      
public class GetReservationsV02Impl implements GetReservationsV02 {

    private static final Logger LOG = Logger.getLogger(GetReservationsV02Impl.class.getName());

    /* (non-Javadoc)
     * @see com.danskebank.services.GetReservationsV02#getReservations(com.danskebank.services.DacGetReservationsInput  dacGetReservationsInput ,)org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType  security ,)com.danskebank.securesoapsgw.RequestHeaderType  requestHeader )*
     */
    public com.danskebank.services.DacGetReservationsOutput getReservations(com.danskebank.services.DacGetReservationsInput dacGetReservationsInput,javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> security,com.danskebank.securesoapsgw.RequestHeaderType requestHeader) { 
        LOG.info("Executing operation getReservations");
        System.out.println(dacGetReservationsInput);
        System.out.println(security.value);
        System.out.println(requestHeader);
        try {
            com.danskebank.services.DacGetReservationsOutput _return = new com.danskebank.services.DacGetReservationsOutput();
            _return.setReturnCode("ReturnCode460363691");
            _return.setReasonCode("ReasonCode1767594221");
            _return.setNumOfTransactions("NumOfTransactions1597211040");
            java.util.List<com.danskebank.services.DacGetReservationsOutput.Transactions> _returnTransactions = new java.util.ArrayList<com.danskebank.services.DacGetReservationsOutput.Transactions>();
            com.danskebank.services.DacGetReservationsOutput.Transactions _returnTransactionsVal1 = new com.danskebank.services.DacGetReservationsOutput.Transactions();
            _returnTransactionsVal1.setTimeStamp("TimeStamp2107710565");
            _returnTransactionsVal1.setOrderId("OrderId801166858");
            _returnTransactionsVal1.setTransactionId("TransactionId-1079738164");
            _returnTransactionsVal1.setAmount(new java.math.BigDecimal("5637344237746184946.3767487953163591133"));
            _returnTransactionsVal1.setCaptureType("CaptureType229710061");
            _returnTransactions.add(_returnTransactionsVal1);
            _return.getTransactions().addAll(_returnTransactions);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
