
package com.danskebank.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:37.801+02:00
 * Generated source version: 3.1.3
 * 
 */
public final class GetReservationsV02_GetReservationsV02_Client {

    private static final QName SERVICE_NAME = new QName("http://www.danskebank.com/services/", "GetReservationsV02Interface");

    private GetReservationsV02_GetReservationsV02_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetReservationsV02Interface.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetReservationsV02Interface ss = new GetReservationsV02Interface(wsdlURL, SERVICE_NAME);
        GetReservationsV02 port = ss.getGetReservationsV02();  
        
        {
        System.out.println("Invoking getReservations...");
        com.danskebank.services.DacGetReservationsInput _getReservations_dacGetReservationsInput = new com.danskebank.services.DacGetReservationsInput();
        _getReservations_dacGetReservationsInput.setMerchantId("MerchantId645258907");
        _getReservations_dacGetReservationsInput.setCustomerId("CustomerId-1496695121");
        _getReservations_dacGetReservationsInput.setTimeStart("TimeStart481908678");
        _getReservations_dacGetReservationsInput.setTimeEnd("TimeEnd1477089595");
        _getReservations_dacGetReservationsInput.setActionCode("ActionCode-965192304");
        _getReservations_dacGetReservationsInput.setTest("Test-1498516210");
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType _getReservations_securityVal = new org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType();
        java.util.List<java.lang.Object> _getReservations_securityValAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _getReservations_securityValAnyVal1 = null;
        _getReservations_securityValAny.add(_getReservations_securityValAnyVal1);
        _getReservations_securityVal.getAny().addAll(_getReservations_securityValAny);
        javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> _getReservations_security = new javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType>(_getReservations_securityVal);
        com.danskebank.securesoapsgw.RequestHeaderType _getReservations_requestHeader = new com.danskebank.securesoapsgw.RequestHeaderType();
        _getReservations_requestHeader.setSenderId("SenderId912136943");
        _getReservations_requestHeader.setSignerId1("SignerId11144631435");
        _getReservations_requestHeader.setSignerId2("SignerId2-985831248");
        _getReservations_requestHeader.setSignerId3("SignerId377287693");
        _getReservations_requestHeader.setDBCryptId("DBCryptId-1138913783");
        _getReservations_requestHeader.setRequestId("RequestId-482571001");
        _getReservations_requestHeader.setTimestamp("Timestamp583521527");
        _getReservations_requestHeader.setLanguage("Language1278024294");
        com.danskebank.services.DacGetReservationsOutput _getReservations__return = port.getReservations(_getReservations_dacGetReservationsInput, _getReservations_security, _getReservations_requestHeader);
        System.out.println("getReservations.result=" + _getReservations__return);

        System.out.println("getReservations._getReservations_security=" + _getReservations_security.value);

        }

        System.exit(0);
    }

}
