package com.danskebank.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:37.874+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "GetReservationsV02Interface", 
                  wsdlLocation = "GetReservationsV02.wsdl",
                  targetNamespace = "http://www.danskebank.com/services/") 
public class GetReservationsV02Interface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.danskebank.com/services/", "GetReservationsV02Interface");
    public final static QName GetReservationsV02 = new QName("http://www.danskebank.com/services/", "GetReservationsV02");
    static {
        URL url = GetReservationsV02Interface.class.getResource("GetReservationsV02.wsdl");
        if (url == null) {
            url = GetReservationsV02Interface.class.getClassLoader().getResource("GetReservationsV02.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(GetReservationsV02Interface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "GetReservationsV02.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public GetReservationsV02Interface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetReservationsV02Interface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetReservationsV02Interface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GetReservationsV02Interface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetReservationsV02Interface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetReservationsV02Interface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GetReservationsV02
     */
    @WebEndpoint(name = "GetReservationsV02")
    public GetReservationsV02 getGetReservationsV02() {
        return super.getPort(GetReservationsV02, GetReservationsV02.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetReservationsV02
     */
    @WebEndpoint(name = "GetReservationsV02")
    public GetReservationsV02 getGetReservationsV02(WebServiceFeature... features) {
        return super.getPort(GetReservationsV02, GetReservationsV02.class, features);
    }

}
