package com.danskebank.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:40.856+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "GetStatusV03Interface", 
                  wsdlLocation = "GetStatusV03.wsdl",
                  targetNamespace = "http://www.danskebank.com/services/") 
public class GetStatusV03Interface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.danskebank.com/services/", "GetStatusV03Interface");
    public final static QName GetStatusV03 = new QName("http://www.danskebank.com/services/", "GetStatusV03");
    static {
        URL url = GetStatusV03Interface.class.getResource("GetStatusV03.wsdl");
        if (url == null) {
            url = GetStatusV03Interface.class.getClassLoader().getResource("GetStatusV03.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(GetStatusV03Interface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "GetStatusV03.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public GetStatusV03Interface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetStatusV03Interface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetStatusV03Interface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GetStatusV03Interface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetStatusV03Interface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetStatusV03Interface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GetStatusV03
     */
    @WebEndpoint(name = "GetStatusV03")
    public GetStatusV03 getGetStatusV03() {
        return super.getPort(GetStatusV03, GetStatusV03.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetStatusV03
     */
    @WebEndpoint(name = "GetStatusV03")
    public GetStatusV03 getGetStatusV03(WebServiceFeature... features) {
        return super.getPort(GetStatusV03, GetStatusV03.class, features);
    }

}
