
package com.danskebank.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:40.794+02:00
 * Generated source version: 3.1.3
 * 
 */
public final class GetStatusV03_GetStatusV03_Client {

    private static final QName SERVICE_NAME = new QName("http://www.danskebank.com/services/", "GetStatusV03Interface");

    private GetStatusV03_GetStatusV03_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetStatusV03Interface.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetStatusV03Interface ss = new GetStatusV03Interface(wsdlURL, SERVICE_NAME);
        GetStatusV03 port = ss.getGetStatusV03();  
        
        {
        System.out.println("Invoking getStatus...");
        com.danskebank.services.DacGetStatusInput _getStatus_dacGetStatusInput = new com.danskebank.services.DacGetStatusInput();
        _getStatus_dacGetStatusInput.setMerchantId("MerchantId1568033407");
        _getStatus_dacGetStatusInput.setOrderId("OrderId-1304503636");
        _getStatus_dacGetStatusInput.setCustomerId("CustomerId-1560749795");
        _getStatus_dacGetStatusInput.setActionCode("ActionCode-2035596345");
        _getStatus_dacGetStatusInput.setTest("Test562960815");
        _getStatus_dacGetStatusInput.setDateFrom("DateFrom1412175645");
        _getStatus_dacGetStatusInput.setDateTo("DateTo-304963254");
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType _getStatus_securityVal = new org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType();
        java.util.List<java.lang.Object> _getStatus_securityValAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _getStatus_securityValAnyVal1 = null;
        _getStatus_securityValAny.add(_getStatus_securityValAnyVal1);
        _getStatus_securityVal.getAny().addAll(_getStatus_securityValAny);
        javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> _getStatus_security = new javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType>(_getStatus_securityVal);
        com.danskebank.securesoapsgw.RequestHeaderType _getStatus_requestHeader = new com.danskebank.securesoapsgw.RequestHeaderType();
        _getStatus_requestHeader.setSenderId("SenderId856142812");
        _getStatus_requestHeader.setSignerId1("SignerId1-1744071683");
        _getStatus_requestHeader.setSignerId2("SignerId2-1219729501");
        _getStatus_requestHeader.setSignerId3("SignerId3-2125334355");
        _getStatus_requestHeader.setDBCryptId("DBCryptId-1861280963");
        _getStatus_requestHeader.setRequestId("RequestId-775235873");
        _getStatus_requestHeader.setTimestamp("Timestamp-241454104");
        _getStatus_requestHeader.setLanguage("Language-1226762909");
        com.danskebank.services.DacGetStatusOutput _getStatus__return = port.getStatus(_getStatus_dacGetStatusInput, _getStatus_security, _getStatus_requestHeader);
        System.out.println("getStatus.result=" + _getStatus__return);

        System.out.println("getStatus._getStatus_security=" + _getStatus_security.value);

        }

        System.exit(0);
    }

}
