
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.danskebank.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:40.840+02:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "GetStatusV03Interface",
                      portName = "GetStatusV03",
                      targetNamespace = "http://www.danskebank.com/services/",
                      wsdlLocation = "GetStatusV03.wsdl",
                      endpointInterface = "com.danskebank.services.GetStatusV03")
                      
public class GetStatusV03Impl implements GetStatusV03 {

    private static final Logger LOG = Logger.getLogger(GetStatusV03Impl.class.getName());

    /* (non-Javadoc)
     * @see com.danskebank.services.GetStatusV03#getStatus(com.danskebank.services.DacGetStatusInput  dacGetStatusInput ,)org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType  security ,)com.danskebank.securesoapsgw.RequestHeaderType  requestHeader )*
     */
    public com.danskebank.services.DacGetStatusOutput getStatus(com.danskebank.services.DacGetStatusInput dacGetStatusInput,javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> security,com.danskebank.securesoapsgw.RequestHeaderType requestHeader) { 
        LOG.info("Executing operation getStatus");
        System.out.println(dacGetStatusInput);
        System.out.println(security.value);
        System.out.println(requestHeader);
        try {
            com.danskebank.services.DacGetStatusOutput _return = new com.danskebank.services.DacGetStatusOutput();
            _return.setReturnCode("ReturnCode-1925871750");
            _return.setReasonCode("ReasonCode950058046");
            _return.setLatestPaymentStatus("LatestPaymentStatus1611443236");
            _return.setOriginalTransactionId("OriginalTransactionId-779880114");
            _return.setOriginalAmount(new java.math.BigDecimal("-2390003343756597651.2358030194205630165"));
            _return.setNumOfTransactions("NumOfTransactions-1650701127");
            java.util.List<com.danskebank.services.DacGetStatusOutput.Transactions> _returnTransactions = new java.util.ArrayList<com.danskebank.services.DacGetStatusOutput.Transactions>();
            com.danskebank.services.DacGetStatusOutput.Transactions _returnTransactionsVal1 = new com.danskebank.services.DacGetStatusOutput.Transactions();
            _returnTransactionsVal1.setTimeStamp("TimeStamp-1351542954");
            _returnTransactionsVal1.setPaymentStatus("PaymentStatus-1959350307");
            _returnTransactionsVal1.setTransactionId("TransactionId-1935077150");
            _returnTransactionsVal1.setAmount(new java.math.BigDecimal("4550860586523674357.8501498592804671776"));
            _returnTransactions.add(_returnTransactionsVal1);
            _return.getTransactions().addAll(_returnTransactions);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
