
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.danskebank.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:43.817+02:00
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "RefundV03Interface",
                      portName = "RefundV03",
                      targetNamespace = "http://www.danskebank.com/services/",
                      wsdlLocation = "RefundV03.wsdl",
                      endpointInterface = "com.danskebank.services.RefundV03")
                      
public class RefundV03Impl implements RefundV03 {

    private static final Logger LOG = Logger.getLogger(RefundV03Impl.class.getName());

    /* (non-Javadoc)
     * @see com.danskebank.services.RefundV03#refund(com.danskebank.services.DacRefundInput  dacRefundInput ,)org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType  security ,)com.danskebank.securesoapsgw.RequestHeaderType  requestHeader )*
     */
    public com.danskebank.services.DacRefundOutput refund(com.danskebank.services.DacRefundInput dacRefundInput,javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> security,com.danskebank.securesoapsgw.RequestHeaderType requestHeader) { 
        LOG.info("Executing operation refund");
        System.out.println(dacRefundInput);
        System.out.println(security.value);
        System.out.println(requestHeader);
        try {
            com.danskebank.services.DacRefundOutput _return = new com.danskebank.services.DacRefundOutput();
            _return.setReturnCode("ReturnCode1162331935");
            _return.setReasonCode("ReasonCode1994040401");
            _return.setTransactionId("TransactionId521017706");
            _return.setOriginalTransactionId("OriginalTransactionId1433582287");
            _return.setRemainderAmount(new java.math.BigDecimal("7363767211222939587.8936725054249030396"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
