
package com.danskebank.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:43.769+02:00
 * Generated source version: 3.1.3
 * 
 */
public final class RefundV03_RefundV03_Client {

    private static final QName SERVICE_NAME = new QName("http://www.danskebank.com/services/", "RefundV03Interface");

    private RefundV03_RefundV03_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RefundV03Interface.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RefundV03Interface ss = new RefundV03Interface(wsdlURL, SERVICE_NAME);
        RefundV03 port = ss.getRefundV03();  
        
        {
        System.out.println("Invoking refund...");
        com.danskebank.services.DacRefundInput _refund_dacRefundInput = new com.danskebank.services.DacRefundInput();
        _refund_dacRefundInput.setDateFrom("DateFrom-26023955");
        _refund_dacRefundInput.setDateTo("DateTo-251336381");
        _refund_dacRefundInput.setBulkRef("BulkRef1830351173");
        _refund_dacRefundInput.setCustomerId("CustomerId-1059247999");
        _refund_dacRefundInput.setMerchantId("MerchantId202652635");
        _refund_dacRefundInput.setOrderId("OrderId-1996345644");
        _refund_dacRefundInput.setAmount(new java.math.BigDecimal("-2839179474904094528.6754011964343010516"));
        _refund_dacRefundInput.setTest("Test2037600052");
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType _refund_securityVal = new org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType();
        java.util.List<java.lang.Object> _refund_securityValAny = new java.util.ArrayList<java.lang.Object>();
        java.lang.Object _refund_securityValAnyVal1 = null;
        _refund_securityValAny.add(_refund_securityValAnyVal1);
        _refund_securityVal.getAny().addAll(_refund_securityValAny);
        javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType> _refund_security = new javax.xml.ws.Holder<org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.SecurityHeaderType>(_refund_securityVal);
        com.danskebank.securesoapsgw.RequestHeaderType _refund_requestHeader = new com.danskebank.securesoapsgw.RequestHeaderType();
        _refund_requestHeader.setSenderId("SenderId1104654100");
        _refund_requestHeader.setSignerId1("SignerId1119128010");
        _refund_requestHeader.setSignerId2("SignerId22127660777");
        _refund_requestHeader.setSignerId3("SignerId31435861047");
        _refund_requestHeader.setDBCryptId("DBCryptId-1860494696");
        _refund_requestHeader.setRequestId("RequestId-1626501720");
        _refund_requestHeader.setTimestamp("Timestamp1199796875");
        _refund_requestHeader.setLanguage("Language468644060");
        com.danskebank.services.DacRefundOutput _refund__return = port.refund(_refund_dacRefundInput, _refund_security, _refund_requestHeader);
        System.out.println("refund.result=" + _refund__return);

        System.out.println("refund._refund_security=" + _refund_security.value);

        }

        System.exit(0);
    }

}
