package com.danskebank.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-07-01T10:13:43.832+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "RefundV03Interface", 
                  wsdlLocation = "RefundV03.wsdl",
                  targetNamespace = "http://www.danskebank.com/services/") 
public class RefundV03Interface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.danskebank.com/services/", "RefundV03Interface");
    public final static QName RefundV03 = new QName("http://www.danskebank.com/services/", "RefundV03");
    static {
        URL url = RefundV03Interface.class.getResource("RefundV03.wsdl");
        if (url == null) {
            url = RefundV03Interface.class.getClassLoader().getResource("RefundV03.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(RefundV03Interface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "RefundV03.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public RefundV03Interface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RefundV03Interface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RefundV03Interface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RefundV03Interface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RefundV03Interface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RefundV03Interface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RefundV03
     */
    @WebEndpoint(name = "RefundV03")
    public RefundV03 getRefundV03() {
        return super.getPort(RefundV03, RefundV03.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundV03
     */
    @WebEndpoint(name = "RefundV03")
    public RefundV03 getRefundV03(WebServiceFeature... features) {
        return super.getPort(RefundV03, RefundV03.class, features);
    }

}
