
package dk.danskebank.pki.pkifactoryservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-28T15:18:54.757+01:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "PKIFactoryServiceFaultElement", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
public class PKIFactoryServiceFault extends Exception {
    
    private dk.danskebank.pki.pkifactoryservice.PKIFactoryServiceFaultDetailType pkiFactoryServiceFaultElement;

    public PKIFactoryServiceFault() {
        super();
    }
    
    public PKIFactoryServiceFault(String message) {
        super(message);
    }
    
    public PKIFactoryServiceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PKIFactoryServiceFault(String message, dk.danskebank.pki.pkifactoryservice.PKIFactoryServiceFaultDetailType pkiFactoryServiceFaultElement) {
        super(message);
        this.pkiFactoryServiceFaultElement = pkiFactoryServiceFaultElement;
    }

    public PKIFactoryServiceFault(String message, dk.danskebank.pki.pkifactoryservice.PKIFactoryServiceFaultDetailType pkiFactoryServiceFaultElement, Throwable cause) {
        super(message, cause);
        this.pkiFactoryServiceFaultElement = pkiFactoryServiceFaultElement;
    }

    public dk.danskebank.pki.pkifactoryservice.PKIFactoryServiceFaultDetailType getFaultInfo() {
        return this.pkiFactoryServiceFaultElement;
    }
}
