package dk.danskebank.pki.pkifactoryservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-28T15:18:54.803+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", name = "PkiServicePortType")
@XmlSeeAlso({ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, org.w3._2001._04.xmlenc_.ObjectFactory.class, dk.danskebank.pki.pkifactoryservice.elements.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PkiServicePortType {

    @WebMethod(operationName = "RenewCertificate", action = "RenewCertificate")
    @WebResult(name = "RenewCertificateOut", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", partName = "RenewCertificateOut")
    public RenewCertificateOutType renewCertificate(
        @WebParam(partName = "RenewCertificateIn", name = "RenewCertificateIn", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
        RenewCertificateInType renewCertificateIn
    ) throws PKIFactoryServiceFault;

    @WebMethod(operationName = "CreateCertificate", action = "CreateCertificate")
    @WebResult(name = "CreateCertificateOut", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", partName = "CreateCertificateOut")
    public CreateCertificateOutType createCertificate(
        @WebParam(partName = "CreateCertificateIn", name = "CreateCertificateIn", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
        CreateCertificateInType createCertificateIn
    ) throws PKIFactoryServiceFault;

    @WebMethod(operationName = "GetOwnCertificateList", action = "GetOwnCertificateList")
    @WebResult(name = "GetOwnCertificateListOut", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", partName = "GetOwnCertificateList")
    public GetOwnCertificateListOutType getOwnCertificateList(
        @WebParam(partName = "GetOwnCertificateListIn", name = "GetOwnCertificateListIn", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
        GetOwnCertificateListInType getOwnCertificateListIn
    ) throws PKIFactoryServiceFault;

    @WebMethod(operationName = "RevokeCertificate", action = "RevokeCertificate")
    @WebResult(name = "RevokeCertificateOut", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", partName = "RevokeCertificateOut")
    public RevokeCertificateOutType revokeCertificate(
        @WebParam(partName = "RevokeCertificateIn", name = "RevokeCertificateIn", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
        RevokeCertificateInType revokeCertificateIn
    ) throws PKIFactoryServiceFault;

    @WebMethod(operationName = "GetBankCertificate", action = "GetBankCertificate")
    @WebResult(name = "GetBankCertificateOut", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", partName = "GetBankCertificateOut")
    public GetBankCertificateOutType getBankCertificate(
        @WebParam(partName = "GetBankCertificateIn", name = "GetBankCertificateIn", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
        GetBankCertificateInType getBankCertificateIn
    ) throws PKIFactoryServiceFault;

    @WebMethod(operationName = "CertificateStatus", action = "CertificateStatus")
    @WebResult(name = "CertificateStatusOut", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService", partName = "CertificateStatusOut")
    public CertificateStatusOutType certificateStatus(
        @WebParam(partName = "CertificateStatusIn", name = "CertificateStatusIn", targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService")
        CertificateStatusInType certificateStatusIn
    ) throws PKIFactoryServiceFault;
}
