
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package dk.danskebank.pki.pkifactoryservice;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-28T15:18:54.768+01:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "PkiService",
                      portName = "PkiServiceHttpPort",
                      targetNamespace = "http://danskebank.dk/PKI/PKIFactoryService",
                      wsdlLocation = "PKIService.wsdl",
                      endpointInterface = "dk.danskebank.pki.pkifactoryservice.PkiServicePortType")
                      
public class PkiServiceHttpPortImpl implements PkiServicePortType {

    private static final Logger LOG = Logger.getLogger(PkiServiceHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see dk.danskebank.pki.pkifactoryservice.PkiServicePortType#renewCertificate(dk.danskebank.pki.pkifactoryservice.RenewCertificateInType  renewCertificateIn )*
     */
    public dk.danskebank.pki.pkifactoryservice.RenewCertificateOutType renewCertificate(RenewCertificateInType renewCertificateIn) throws PKIFactoryServiceFault    { 
        LOG.info("Executing operation renewCertificate");
        System.out.println(renewCertificateIn);
        try {
            dk.danskebank.pki.pkifactoryservice.RenewCertificateOutType _return = new dk.danskebank.pki.pkifactoryservice.RenewCertificateOutType();
            dk.danskebank.pki.pkifactoryservice.ResponseHeaderType _returnResponseHeader = new dk.danskebank.pki.pkifactoryservice.ResponseHeaderType();
            _returnResponseHeader.setSenderId("SenderId-937048998");
            _returnResponseHeader.setCustomerId("CustomerId-676809173");
            _returnResponseHeader.setRequestId("RequestId-903441873");
            _returnResponseHeader.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.781+01:00"));
            _returnResponseHeader.setInterfaceVersion("InterfaceVersion-434034509");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnResponseHeaderEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.CUSTOMERTEST;
            _returnResponseHeader.setEnvironment(_returnResponseHeaderEnvironment);
            _return.setResponseHeader(_returnResponseHeader);
            dk.danskebank.pki.pkifactoryservice.elements.RenewCertificateResponse _returnRenewCertificateResponse = new dk.danskebank.pki.pkifactoryservice.elements.RenewCertificateResponse();
            _returnRenewCertificateResponse.setReturnCode("ReturnCode1389217405");
            _returnRenewCertificateResponse.setReturnText("ReturnText409735226");
            byte[] _returnRenewCertificateResponseEncryptionCert = new byte[] {};
            _returnRenewCertificateResponse.setEncryptionCert(_returnRenewCertificateResponseEncryptionCert);
            byte[] _returnRenewCertificateResponseSigningCert = new byte[] {};
            _returnRenewCertificateResponse.setSigningCert(_returnRenewCertificateResponseSigningCert);
            byte[] _returnRenewCertificateResponseCACert = new byte[] {};
            _returnRenewCertificateResponse.setCACert(_returnRenewCertificateResponseCACert);
            _returnRenewCertificateResponse.setRequestId("RequestId-1558792045");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnRenewCertificateResponseEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.CUSTOMERTEST;
            _returnRenewCertificateResponse.setEnvironment(_returnRenewCertificateResponseEnvironment);
            org.w3._2000._09.xmldsig_.SignatureType _returnRenewCertificateResponseSignature = new org.w3._2000._09.xmldsig_.SignatureType();
            org.w3._2000._09.xmldsig_.SignedInfoType _returnRenewCertificateResponseSignatureSignedInfo = new org.w3._2000._09.xmldsig_.SignedInfoType();
            org.w3._2000._09.xmldsig_.CanonicalizationMethodType _returnRenewCertificateResponseSignatureSignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig_.CanonicalizationMethodType();
            java.util.List<java.lang.Object> _returnRenewCertificateResponseSignatureSignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnRenewCertificateResponseSignatureSignedInfoCanonicalizationMethod.getContent().addAll(_returnRenewCertificateResponseSignatureSignedInfoCanonicalizationMethodContent);
            _returnRenewCertificateResponseSignatureSignedInfoCanonicalizationMethod.setAlgorithm("Algorithm1113002088");
            _returnRenewCertificateResponseSignatureSignedInfo.setCanonicalizationMethod(_returnRenewCertificateResponseSignatureSignedInfoCanonicalizationMethod);
            org.w3._2000._09.xmldsig_.SignatureMethodType _returnRenewCertificateResponseSignatureSignedInfoSignatureMethod = new org.w3._2000._09.xmldsig_.SignatureMethodType();
            java.util.List<java.lang.Object> _returnRenewCertificateResponseSignatureSignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnRenewCertificateResponseSignatureSignedInfoSignatureMethod.getContent().addAll(_returnRenewCertificateResponseSignatureSignedInfoSignatureMethodContent);
            _returnRenewCertificateResponseSignatureSignedInfoSignatureMethod.setAlgorithm("Algorithm508376479");
            _returnRenewCertificateResponseSignatureSignedInfo.setSignatureMethod(_returnRenewCertificateResponseSignatureSignedInfoSignatureMethod);
            java.util.List<org.w3._2000._09.xmldsig_.ReferenceType> _returnRenewCertificateResponseSignatureSignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ReferenceType>();
            _returnRenewCertificateResponseSignatureSignedInfo.getReference().addAll(_returnRenewCertificateResponseSignatureSignedInfoReference);
            _returnRenewCertificateResponseSignatureSignedInfo.setId("Id-1942424651");
            _returnRenewCertificateResponseSignature.setSignedInfo(_returnRenewCertificateResponseSignatureSignedInfo);
            org.w3._2000._09.xmldsig_.SignatureValueType _returnRenewCertificateResponseSignatureSignatureValue = new org.w3._2000._09.xmldsig_.SignatureValueType();
            byte[] _returnRenewCertificateResponseSignatureSignatureValueValue = new byte[] {};
            _returnRenewCertificateResponseSignatureSignatureValue.setValue(_returnRenewCertificateResponseSignatureSignatureValueValue);
            _returnRenewCertificateResponseSignatureSignatureValue.setId("Id143584838");
            _returnRenewCertificateResponseSignature.setSignatureValue(_returnRenewCertificateResponseSignatureSignatureValue);
            org.w3._2000._09.xmldsig_.KeyInfoType _returnRenewCertificateResponseSignatureKeyInfo = new org.w3._2000._09.xmldsig_.KeyInfoType();
            java.util.List<java.lang.Object> _returnRenewCertificateResponseSignatureKeyInfoContent = new java.util.ArrayList<java.lang.Object>();
            _returnRenewCertificateResponseSignatureKeyInfo.getContent().addAll(_returnRenewCertificateResponseSignatureKeyInfoContent);
            _returnRenewCertificateResponseSignatureKeyInfo.setId("Id-1282014168");
            _returnRenewCertificateResponseSignature.setKeyInfo(_returnRenewCertificateResponseSignatureKeyInfo);
            java.util.List<org.w3._2000._09.xmldsig_.ObjectType> _returnRenewCertificateResponseSignatureObject = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ObjectType>();
            _returnRenewCertificateResponseSignature.getObject().addAll(_returnRenewCertificateResponseSignatureObject);
            _returnRenewCertificateResponseSignature.setId("Id-1892222269");
            _returnRenewCertificateResponse.setSignature(_returnRenewCertificateResponseSignature);
            _returnRenewCertificateResponse.setId("Id1263193366");
            _return.setRenewCertificateResponse(_returnRenewCertificateResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PKIFactoryServiceFault("PKIFactoryServiceFault...");
    }

    /* (non-Javadoc)
     * @see dk.danskebank.pki.pkifactoryservice.PkiServicePortType#createCertificate(dk.danskebank.pki.pkifactoryservice.CreateCertificateInType  createCertificateIn )*
     */
    public dk.danskebank.pki.pkifactoryservice.CreateCertificateOutType createCertificate(CreateCertificateInType createCertificateIn) throws PKIFactoryServiceFault    { 
        LOG.info("Executing operation createCertificate");
        System.out.println(createCertificateIn);
        try {
            dk.danskebank.pki.pkifactoryservice.CreateCertificateOutType _return = new dk.danskebank.pki.pkifactoryservice.CreateCertificateOutType();
            dk.danskebank.pki.pkifactoryservice.ResponseHeaderType _returnResponseHeader = new dk.danskebank.pki.pkifactoryservice.ResponseHeaderType();
            _returnResponseHeader.setSenderId("SenderId-706391930");
            _returnResponseHeader.setCustomerId("CustomerId-1370246763");
            _returnResponseHeader.setRequestId("RequestId-1530718882");
            _returnResponseHeader.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.784+01:00"));
            _returnResponseHeader.setInterfaceVersion("InterfaceVersion-680288345");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnResponseHeaderEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.PRODUCTION;
            _returnResponseHeader.setEnvironment(_returnResponseHeaderEnvironment);
            _return.setResponseHeader(_returnResponseHeader);
            dk.danskebank.pki.pkifactoryservice.elements.CreateCertificateResponse _returnCreateCertificateResponse = new dk.danskebank.pki.pkifactoryservice.elements.CreateCertificateResponse();
            _returnCreateCertificateResponse.setReturnCode("ReturnCode879706464");
            _returnCreateCertificateResponse.setReturnText("ReturnText416592495");
            byte[] _returnCreateCertificateResponseEncryptionCert = new byte[] {};
            _returnCreateCertificateResponse.setEncryptionCert(_returnCreateCertificateResponseEncryptionCert);
            byte[] _returnCreateCertificateResponseSigningCert = new byte[] {};
            _returnCreateCertificateResponse.setSigningCert(_returnCreateCertificateResponseSigningCert);
            byte[] _returnCreateCertificateResponseCACert = new byte[] {};
            _returnCreateCertificateResponse.setCACert(_returnCreateCertificateResponseCACert);
            _returnCreateCertificateResponse.setRequestId("RequestId-948202708");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnCreateCertificateResponseEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.SYSTEMTEST;
            _returnCreateCertificateResponse.setEnvironment(_returnCreateCertificateResponseEnvironment);
            org.w3._2000._09.xmldsig_.SignatureType _returnCreateCertificateResponseSignature = new org.w3._2000._09.xmldsig_.SignatureType();
            org.w3._2000._09.xmldsig_.SignedInfoType _returnCreateCertificateResponseSignatureSignedInfo = new org.w3._2000._09.xmldsig_.SignedInfoType();
            org.w3._2000._09.xmldsig_.CanonicalizationMethodType _returnCreateCertificateResponseSignatureSignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig_.CanonicalizationMethodType();
            java.util.List<java.lang.Object> _returnCreateCertificateResponseSignatureSignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnCreateCertificateResponseSignatureSignedInfoCanonicalizationMethod.getContent().addAll(_returnCreateCertificateResponseSignatureSignedInfoCanonicalizationMethodContent);
            _returnCreateCertificateResponseSignatureSignedInfoCanonicalizationMethod.setAlgorithm("Algorithm2115255964");
            _returnCreateCertificateResponseSignatureSignedInfo.setCanonicalizationMethod(_returnCreateCertificateResponseSignatureSignedInfoCanonicalizationMethod);
            org.w3._2000._09.xmldsig_.SignatureMethodType _returnCreateCertificateResponseSignatureSignedInfoSignatureMethod = new org.w3._2000._09.xmldsig_.SignatureMethodType();
            java.util.List<java.lang.Object> _returnCreateCertificateResponseSignatureSignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnCreateCertificateResponseSignatureSignedInfoSignatureMethod.getContent().addAll(_returnCreateCertificateResponseSignatureSignedInfoSignatureMethodContent);
            _returnCreateCertificateResponseSignatureSignedInfoSignatureMethod.setAlgorithm("Algorithm-864920721");
            _returnCreateCertificateResponseSignatureSignedInfo.setSignatureMethod(_returnCreateCertificateResponseSignatureSignedInfoSignatureMethod);
            java.util.List<org.w3._2000._09.xmldsig_.ReferenceType> _returnCreateCertificateResponseSignatureSignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ReferenceType>();
            _returnCreateCertificateResponseSignatureSignedInfo.getReference().addAll(_returnCreateCertificateResponseSignatureSignedInfoReference);
            _returnCreateCertificateResponseSignatureSignedInfo.setId("Id-2073105561");
            _returnCreateCertificateResponseSignature.setSignedInfo(_returnCreateCertificateResponseSignatureSignedInfo);
            org.w3._2000._09.xmldsig_.SignatureValueType _returnCreateCertificateResponseSignatureSignatureValue = new org.w3._2000._09.xmldsig_.SignatureValueType();
            byte[] _returnCreateCertificateResponseSignatureSignatureValueValue = new byte[] {};
            _returnCreateCertificateResponseSignatureSignatureValue.setValue(_returnCreateCertificateResponseSignatureSignatureValueValue);
            _returnCreateCertificateResponseSignatureSignatureValue.setId("Id-137015562");
            _returnCreateCertificateResponseSignature.setSignatureValue(_returnCreateCertificateResponseSignatureSignatureValue);
            org.w3._2000._09.xmldsig_.KeyInfoType _returnCreateCertificateResponseSignatureKeyInfo = new org.w3._2000._09.xmldsig_.KeyInfoType();
            java.util.List<java.lang.Object> _returnCreateCertificateResponseSignatureKeyInfoContent = new java.util.ArrayList<java.lang.Object>();
            _returnCreateCertificateResponseSignatureKeyInfo.getContent().addAll(_returnCreateCertificateResponseSignatureKeyInfoContent);
            _returnCreateCertificateResponseSignatureKeyInfo.setId("Id491615360");
            _returnCreateCertificateResponseSignature.setKeyInfo(_returnCreateCertificateResponseSignatureKeyInfo);
            java.util.List<org.w3._2000._09.xmldsig_.ObjectType> _returnCreateCertificateResponseSignatureObject = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ObjectType>();
            _returnCreateCertificateResponseSignature.getObject().addAll(_returnCreateCertificateResponseSignatureObject);
            _returnCreateCertificateResponseSignature.setId("Id1228700361");
            _returnCreateCertificateResponse.setSignature(_returnCreateCertificateResponseSignature);
            _returnCreateCertificateResponse.setId("Id-1761303179");
            _return.setCreateCertificateResponse(_returnCreateCertificateResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PKIFactoryServiceFault("PKIFactoryServiceFault...");
    }

    /* (non-Javadoc)
     * @see dk.danskebank.pki.pkifactoryservice.PkiServicePortType#getOwnCertificateList(dk.danskebank.pki.pkifactoryservice.GetOwnCertificateListInType  getOwnCertificateListIn )*
     */
    public dk.danskebank.pki.pkifactoryservice.GetOwnCertificateListOutType getOwnCertificateList(GetOwnCertificateListInType getOwnCertificateListIn) throws PKIFactoryServiceFault    { 
        LOG.info("Executing operation getOwnCertificateList");
        System.out.println(getOwnCertificateListIn);
        try {
            dk.danskebank.pki.pkifactoryservice.GetOwnCertificateListOutType _return = new dk.danskebank.pki.pkifactoryservice.GetOwnCertificateListOutType();
            dk.danskebank.pki.pkifactoryservice.ResponseHeaderType _returnResponseHeader = new dk.danskebank.pki.pkifactoryservice.ResponseHeaderType();
            _returnResponseHeader.setSenderId("SenderId1345627586");
            _returnResponseHeader.setCustomerId("CustomerId348218475");
            _returnResponseHeader.setRequestId("RequestId90387336");
            _returnResponseHeader.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.787+01:00"));
            _returnResponseHeader.setInterfaceVersion("InterfaceVersion1762068343");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnResponseHeaderEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.SYSTEMTEST;
            _returnResponseHeader.setEnvironment(_returnResponseHeaderEnvironment);
            _return.setResponseHeader(_returnResponseHeader);
            dk.danskebank.pki.pkifactoryservice.elements.GetOwnCertificateListResponse _returnGetOwnCertificateListResponse = new dk.danskebank.pki.pkifactoryservice.elements.GetOwnCertificateListResponse();
            _returnGetOwnCertificateListResponse.setReturnCode("ReturnCode1857132583");
            _returnGetOwnCertificateListResponse.setReturnText("ReturnText-520781742");
            java.util.List<dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType> _returnGetOwnCertificateListResponseCertificateStatus = new java.util.ArrayList<dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType>();
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType _returnGetOwnCertificateListResponseCertificateStatusVal1 = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType();
            _returnGetOwnCertificateListResponseCertificateStatusVal1.setCertificateSerialNo("CertificateSerialNo-691861901");
            dk.danskebank.pki.pkifactoryservice.elements.CertificateTypeType _returnGetOwnCertificateListResponseCertificateStatusVal1CertificateType = dk.danskebank.pki.pkifactoryservice.elements.CertificateTypeType.SIGNING;
            _returnGetOwnCertificateListResponseCertificateStatusVal1.setCertificateType(_returnGetOwnCertificateListResponseCertificateStatusVal1CertificateType);
            _returnGetOwnCertificateListResponseCertificateStatusVal1.setMatchingCertificateSerialNo("MatchingCertificateSerialNo-1020898191");
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status _returnGetOwnCertificateListResponseCertificateStatusVal1Status = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status();
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Good _returnGetOwnCertificateListResponseCertificateStatusVal1StatusGood = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Good();
            _returnGetOwnCertificateListResponseCertificateStatusVal1StatusGood.setExpiryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.788+01:00"));
            _returnGetOwnCertificateListResponseCertificateStatusVal1Status.setGood(_returnGetOwnCertificateListResponseCertificateStatusVal1StatusGood);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.ExpiresSoon _returnGetOwnCertificateListResponseCertificateStatusVal1StatusExpiresSoon = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.ExpiresSoon();
            _returnGetOwnCertificateListResponseCertificateStatusVal1StatusExpiresSoon.setExpiryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.789+01:00"));
            _returnGetOwnCertificateListResponseCertificateStatusVal1Status.setExpiresSoon(_returnGetOwnCertificateListResponseCertificateStatusVal1StatusExpiresSoon);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Expired _returnGetOwnCertificateListResponseCertificateStatusVal1StatusExpired = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Expired();
            _returnGetOwnCertificateListResponseCertificateStatusVal1StatusExpired.setExpiryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.789+01:00"));
            _returnGetOwnCertificateListResponseCertificateStatusVal1Status.setExpired(_returnGetOwnCertificateListResponseCertificateStatusVal1StatusExpired);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Revoked _returnGetOwnCertificateListResponseCertificateStatusVal1StatusRevoked = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Revoked();
            _returnGetOwnCertificateListResponseCertificateStatusVal1StatusRevoked.setRevocationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.789+01:00"));
            _returnGetOwnCertificateListResponseCertificateStatusVal1StatusRevoked.setCRLReason(new java.math.BigInteger("-78861398633256288034607411153235374009"));
            _returnGetOwnCertificateListResponseCertificateStatusVal1Status.setRevoked(_returnGetOwnCertificateListResponseCertificateStatusVal1StatusRevoked);
            _returnGetOwnCertificateListResponseCertificateStatusVal1.setStatus(_returnGetOwnCertificateListResponseCertificateStatusVal1Status);
            _returnGetOwnCertificateListResponseCertificateStatus.add(_returnGetOwnCertificateListResponseCertificateStatusVal1);
            _returnGetOwnCertificateListResponse.getCertificateStatus().addAll(_returnGetOwnCertificateListResponseCertificateStatus);
            _returnGetOwnCertificateListResponse.setRequestId("RequestId-133725442");
            org.w3._2000._09.xmldsig_.SignatureType _returnGetOwnCertificateListResponseSignature = new org.w3._2000._09.xmldsig_.SignatureType();
            org.w3._2000._09.xmldsig_.SignedInfoType _returnGetOwnCertificateListResponseSignatureSignedInfo = new org.w3._2000._09.xmldsig_.SignedInfoType();
            org.w3._2000._09.xmldsig_.CanonicalizationMethodType _returnGetOwnCertificateListResponseSignatureSignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig_.CanonicalizationMethodType();
            java.util.List<java.lang.Object> _returnGetOwnCertificateListResponseSignatureSignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnGetOwnCertificateListResponseSignatureSignedInfoCanonicalizationMethod.getContent().addAll(_returnGetOwnCertificateListResponseSignatureSignedInfoCanonicalizationMethodContent);
            _returnGetOwnCertificateListResponseSignatureSignedInfoCanonicalizationMethod.setAlgorithm("Algorithm-256067311");
            _returnGetOwnCertificateListResponseSignatureSignedInfo.setCanonicalizationMethod(_returnGetOwnCertificateListResponseSignatureSignedInfoCanonicalizationMethod);
            org.w3._2000._09.xmldsig_.SignatureMethodType _returnGetOwnCertificateListResponseSignatureSignedInfoSignatureMethod = new org.w3._2000._09.xmldsig_.SignatureMethodType();
            java.util.List<java.lang.Object> _returnGetOwnCertificateListResponseSignatureSignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnGetOwnCertificateListResponseSignatureSignedInfoSignatureMethod.getContent().addAll(_returnGetOwnCertificateListResponseSignatureSignedInfoSignatureMethodContent);
            _returnGetOwnCertificateListResponseSignatureSignedInfoSignatureMethod.setAlgorithm("Algorithm1568553164");
            _returnGetOwnCertificateListResponseSignatureSignedInfo.setSignatureMethod(_returnGetOwnCertificateListResponseSignatureSignedInfoSignatureMethod);
            java.util.List<org.w3._2000._09.xmldsig_.ReferenceType> _returnGetOwnCertificateListResponseSignatureSignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ReferenceType>();
            _returnGetOwnCertificateListResponseSignatureSignedInfo.getReference().addAll(_returnGetOwnCertificateListResponseSignatureSignedInfoReference);
            _returnGetOwnCertificateListResponseSignatureSignedInfo.setId("Id-1889316571");
            _returnGetOwnCertificateListResponseSignature.setSignedInfo(_returnGetOwnCertificateListResponseSignatureSignedInfo);
            org.w3._2000._09.xmldsig_.SignatureValueType _returnGetOwnCertificateListResponseSignatureSignatureValue = new org.w3._2000._09.xmldsig_.SignatureValueType();
            byte[] _returnGetOwnCertificateListResponseSignatureSignatureValueValue = new byte[] {};
            _returnGetOwnCertificateListResponseSignatureSignatureValue.setValue(_returnGetOwnCertificateListResponseSignatureSignatureValueValue);
            _returnGetOwnCertificateListResponseSignatureSignatureValue.setId("Id-2128596943");
            _returnGetOwnCertificateListResponseSignature.setSignatureValue(_returnGetOwnCertificateListResponseSignatureSignatureValue);
            org.w3._2000._09.xmldsig_.KeyInfoType _returnGetOwnCertificateListResponseSignatureKeyInfo = new org.w3._2000._09.xmldsig_.KeyInfoType();
            java.util.List<java.lang.Object> _returnGetOwnCertificateListResponseSignatureKeyInfoContent = new java.util.ArrayList<java.lang.Object>();
            _returnGetOwnCertificateListResponseSignatureKeyInfo.getContent().addAll(_returnGetOwnCertificateListResponseSignatureKeyInfoContent);
            _returnGetOwnCertificateListResponseSignatureKeyInfo.setId("Id1575132611");
            _returnGetOwnCertificateListResponseSignature.setKeyInfo(_returnGetOwnCertificateListResponseSignatureKeyInfo);
            java.util.List<org.w3._2000._09.xmldsig_.ObjectType> _returnGetOwnCertificateListResponseSignatureObject = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ObjectType>();
            _returnGetOwnCertificateListResponseSignature.getObject().addAll(_returnGetOwnCertificateListResponseSignatureObject);
            _returnGetOwnCertificateListResponseSignature.setId("Id-300394562");
            _returnGetOwnCertificateListResponse.setSignature(_returnGetOwnCertificateListResponseSignature);
            _returnGetOwnCertificateListResponse.setId("Id-1739236389");
            _return.setGetOwnCertificateListResponse(_returnGetOwnCertificateListResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PKIFactoryServiceFault("PKIFactoryServiceFault...");
    }

    /* (non-Javadoc)
     * @see dk.danskebank.pki.pkifactoryservice.PkiServicePortType#revokeCertificate(dk.danskebank.pki.pkifactoryservice.RevokeCertificateInType  revokeCertificateIn )*
     */
    public dk.danskebank.pki.pkifactoryservice.RevokeCertificateOutType revokeCertificate(RevokeCertificateInType revokeCertificateIn) throws PKIFactoryServiceFault    { 
        LOG.info("Executing operation revokeCertificate");
        System.out.println(revokeCertificateIn);
        try {
            dk.danskebank.pki.pkifactoryservice.RevokeCertificateOutType _return = new dk.danskebank.pki.pkifactoryservice.RevokeCertificateOutType();
            dk.danskebank.pki.pkifactoryservice.ResponseHeaderType _returnResponseHeader = new dk.danskebank.pki.pkifactoryservice.ResponseHeaderType();
            _returnResponseHeader.setSenderId("SenderId627462327");
            _returnResponseHeader.setCustomerId("CustomerId-487397095");
            _returnResponseHeader.setRequestId("RequestId545632656");
            _returnResponseHeader.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.792+01:00"));
            _returnResponseHeader.setInterfaceVersion("InterfaceVersion-1498068353");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnResponseHeaderEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.SYSTEMTEST;
            _returnResponseHeader.setEnvironment(_returnResponseHeaderEnvironment);
            _return.setResponseHeader(_returnResponseHeader);
            dk.danskebank.pki.pkifactoryservice.elements.RevokeCertificateResponse _returnRevokeCertificateResponse = new dk.danskebank.pki.pkifactoryservice.elements.RevokeCertificateResponse();
            _returnRevokeCertificateResponse.setReturnCode("ReturnCode-1850731081");
            _returnRevokeCertificateResponse.setReturnText("ReturnText-1686939226");
            java.util.List<java.lang.String> _returnRevokeCertificateResponseCertificateSerialNo = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnRevokeCertificateResponseCertificateSerialNoVal1 = "_returnRevokeCertificateResponseCertificateSerialNoVal439303930";
            _returnRevokeCertificateResponseCertificateSerialNo.add(_returnRevokeCertificateResponseCertificateSerialNoVal1);
            _returnRevokeCertificateResponse.getCertificateSerialNo().addAll(_returnRevokeCertificateResponseCertificateSerialNo);
            _returnRevokeCertificateResponse.setRevocationTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.793+01:00"));
            _returnRevokeCertificateResponse.setRequestId("RequestId-1990062119");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnRevokeCertificateResponseEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.CUSTOMERTEST;
            _returnRevokeCertificateResponse.setEnvironment(_returnRevokeCertificateResponseEnvironment);
            org.w3._2000._09.xmldsig_.SignatureType _returnRevokeCertificateResponseSignature = new org.w3._2000._09.xmldsig_.SignatureType();
            org.w3._2000._09.xmldsig_.SignedInfoType _returnRevokeCertificateResponseSignatureSignedInfo = new org.w3._2000._09.xmldsig_.SignedInfoType();
            org.w3._2000._09.xmldsig_.CanonicalizationMethodType _returnRevokeCertificateResponseSignatureSignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig_.CanonicalizationMethodType();
            java.util.List<java.lang.Object> _returnRevokeCertificateResponseSignatureSignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnRevokeCertificateResponseSignatureSignedInfoCanonicalizationMethod.getContent().addAll(_returnRevokeCertificateResponseSignatureSignedInfoCanonicalizationMethodContent);
            _returnRevokeCertificateResponseSignatureSignedInfoCanonicalizationMethod.setAlgorithm("Algorithm1498884000");
            _returnRevokeCertificateResponseSignatureSignedInfo.setCanonicalizationMethod(_returnRevokeCertificateResponseSignatureSignedInfoCanonicalizationMethod);
            org.w3._2000._09.xmldsig_.SignatureMethodType _returnRevokeCertificateResponseSignatureSignedInfoSignatureMethod = new org.w3._2000._09.xmldsig_.SignatureMethodType();
            java.util.List<java.lang.Object> _returnRevokeCertificateResponseSignatureSignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnRevokeCertificateResponseSignatureSignedInfoSignatureMethod.getContent().addAll(_returnRevokeCertificateResponseSignatureSignedInfoSignatureMethodContent);
            _returnRevokeCertificateResponseSignatureSignedInfoSignatureMethod.setAlgorithm("Algorithm551848573");
            _returnRevokeCertificateResponseSignatureSignedInfo.setSignatureMethod(_returnRevokeCertificateResponseSignatureSignedInfoSignatureMethod);
            java.util.List<org.w3._2000._09.xmldsig_.ReferenceType> _returnRevokeCertificateResponseSignatureSignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ReferenceType>();
            _returnRevokeCertificateResponseSignatureSignedInfo.getReference().addAll(_returnRevokeCertificateResponseSignatureSignedInfoReference);
            _returnRevokeCertificateResponseSignatureSignedInfo.setId("Id-1641072097");
            _returnRevokeCertificateResponseSignature.setSignedInfo(_returnRevokeCertificateResponseSignatureSignedInfo);
            org.w3._2000._09.xmldsig_.SignatureValueType _returnRevokeCertificateResponseSignatureSignatureValue = new org.w3._2000._09.xmldsig_.SignatureValueType();
            byte[] _returnRevokeCertificateResponseSignatureSignatureValueValue = new byte[] {};
            _returnRevokeCertificateResponseSignatureSignatureValue.setValue(_returnRevokeCertificateResponseSignatureSignatureValueValue);
            _returnRevokeCertificateResponseSignatureSignatureValue.setId("Id-1773385108");
            _returnRevokeCertificateResponseSignature.setSignatureValue(_returnRevokeCertificateResponseSignatureSignatureValue);
            org.w3._2000._09.xmldsig_.KeyInfoType _returnRevokeCertificateResponseSignatureKeyInfo = new org.w3._2000._09.xmldsig_.KeyInfoType();
            java.util.List<java.lang.Object> _returnRevokeCertificateResponseSignatureKeyInfoContent = new java.util.ArrayList<java.lang.Object>();
            _returnRevokeCertificateResponseSignatureKeyInfo.getContent().addAll(_returnRevokeCertificateResponseSignatureKeyInfoContent);
            _returnRevokeCertificateResponseSignatureKeyInfo.setId("Id902246967");
            _returnRevokeCertificateResponseSignature.setKeyInfo(_returnRevokeCertificateResponseSignatureKeyInfo);
            java.util.List<org.w3._2000._09.xmldsig_.ObjectType> _returnRevokeCertificateResponseSignatureObject = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ObjectType>();
            _returnRevokeCertificateResponseSignature.getObject().addAll(_returnRevokeCertificateResponseSignatureObject);
            _returnRevokeCertificateResponseSignature.setId("Id-1854574139");
            _returnRevokeCertificateResponse.setSignature(_returnRevokeCertificateResponseSignature);
            _returnRevokeCertificateResponse.setId("Id686184884");
            _return.setRevokeCertificateResponse(_returnRevokeCertificateResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PKIFactoryServiceFault("PKIFactoryServiceFault...");
    }

    /* (non-Javadoc)
     * @see dk.danskebank.pki.pkifactoryservice.PkiServicePortType#getBankCertificate(dk.danskebank.pki.pkifactoryservice.GetBankCertificateInType  getBankCertificateIn )*
     */
    public dk.danskebank.pki.pkifactoryservice.GetBankCertificateOutType getBankCertificate(GetBankCertificateInType getBankCertificateIn) throws PKIFactoryServiceFault    { 
        LOG.info("Executing operation getBankCertificate");
        System.out.println(getBankCertificateIn);
        try {
            dk.danskebank.pki.pkifactoryservice.GetBankCertificateOutType _return = new dk.danskebank.pki.pkifactoryservice.GetBankCertificateOutType();
            dk.danskebank.pki.pkifactoryservice.ResponseHeaderType _returnResponseHeader = new dk.danskebank.pki.pkifactoryservice.ResponseHeaderType();
            _returnResponseHeader.setSenderId("SenderId862461967");
            _returnResponseHeader.setCustomerId("CustomerId1867359052");
            _returnResponseHeader.setRequestId("RequestId1563193760");
            _returnResponseHeader.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.796+01:00"));
            _returnResponseHeader.setInterfaceVersion("InterfaceVersion-1404246351");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnResponseHeaderEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.TEST;
            _returnResponseHeader.setEnvironment(_returnResponseHeaderEnvironment);
            _return.setResponseHeader(_returnResponseHeader);
            dk.danskebank.pki.pkifactoryservice.elements.GetBankCertificateResponse _returnGetBankCertificateResponse = new dk.danskebank.pki.pkifactoryservice.elements.GetBankCertificateResponse();
            _returnGetBankCertificateResponse.setReturnCode("ReturnCode-1583531714");
            _returnGetBankCertificateResponse.setReturnText("ReturnText1442498479");
            byte[] _returnGetBankCertificateResponseBankEncryptionCert = new byte[] {};
            _returnGetBankCertificateResponse.setBankEncryptionCert(_returnGetBankCertificateResponseBankEncryptionCert);
            byte[] _returnGetBankCertificateResponseBankSigningCert = new byte[] {};
            _returnGetBankCertificateResponse.setBankSigningCert(_returnGetBankCertificateResponseBankSigningCert);
            byte[] _returnGetBankCertificateResponseBankRootCert = new byte[] {};
            _returnGetBankCertificateResponse.setBankRootCert(_returnGetBankCertificateResponseBankRootCert);
            _returnGetBankCertificateResponse.setRequestId("RequestId915547406");
            org.w3._2000._09.xmldsig_.SignatureType _returnGetBankCertificateResponseSignature = new org.w3._2000._09.xmldsig_.SignatureType();
            org.w3._2000._09.xmldsig_.SignedInfoType _returnGetBankCertificateResponseSignatureSignedInfo = new org.w3._2000._09.xmldsig_.SignedInfoType();
            org.w3._2000._09.xmldsig_.CanonicalizationMethodType _returnGetBankCertificateResponseSignatureSignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig_.CanonicalizationMethodType();
            java.util.List<java.lang.Object> _returnGetBankCertificateResponseSignatureSignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnGetBankCertificateResponseSignatureSignedInfoCanonicalizationMethod.getContent().addAll(_returnGetBankCertificateResponseSignatureSignedInfoCanonicalizationMethodContent);
            _returnGetBankCertificateResponseSignatureSignedInfoCanonicalizationMethod.setAlgorithm("Algorithm909154184");
            _returnGetBankCertificateResponseSignatureSignedInfo.setCanonicalizationMethod(_returnGetBankCertificateResponseSignatureSignedInfoCanonicalizationMethod);
            org.w3._2000._09.xmldsig_.SignatureMethodType _returnGetBankCertificateResponseSignatureSignedInfoSignatureMethod = new org.w3._2000._09.xmldsig_.SignatureMethodType();
            java.util.List<java.lang.Object> _returnGetBankCertificateResponseSignatureSignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnGetBankCertificateResponseSignatureSignedInfoSignatureMethod.getContent().addAll(_returnGetBankCertificateResponseSignatureSignedInfoSignatureMethodContent);
            _returnGetBankCertificateResponseSignatureSignedInfoSignatureMethod.setAlgorithm("Algorithm628885883");
            _returnGetBankCertificateResponseSignatureSignedInfo.setSignatureMethod(_returnGetBankCertificateResponseSignatureSignedInfoSignatureMethod);
            java.util.List<org.w3._2000._09.xmldsig_.ReferenceType> _returnGetBankCertificateResponseSignatureSignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ReferenceType>();
            _returnGetBankCertificateResponseSignatureSignedInfo.getReference().addAll(_returnGetBankCertificateResponseSignatureSignedInfoReference);
            _returnGetBankCertificateResponseSignatureSignedInfo.setId("Id-1464974484");
            _returnGetBankCertificateResponseSignature.setSignedInfo(_returnGetBankCertificateResponseSignatureSignedInfo);
            org.w3._2000._09.xmldsig_.SignatureValueType _returnGetBankCertificateResponseSignatureSignatureValue = new org.w3._2000._09.xmldsig_.SignatureValueType();
            byte[] _returnGetBankCertificateResponseSignatureSignatureValueValue = new byte[] {};
            _returnGetBankCertificateResponseSignatureSignatureValue.setValue(_returnGetBankCertificateResponseSignatureSignatureValueValue);
            _returnGetBankCertificateResponseSignatureSignatureValue.setId("Id-340608170");
            _returnGetBankCertificateResponseSignature.setSignatureValue(_returnGetBankCertificateResponseSignatureSignatureValue);
            org.w3._2000._09.xmldsig_.KeyInfoType _returnGetBankCertificateResponseSignatureKeyInfo = new org.w3._2000._09.xmldsig_.KeyInfoType();
            java.util.List<java.lang.Object> _returnGetBankCertificateResponseSignatureKeyInfoContent = new java.util.ArrayList<java.lang.Object>();
            _returnGetBankCertificateResponseSignatureKeyInfo.getContent().addAll(_returnGetBankCertificateResponseSignatureKeyInfoContent);
            _returnGetBankCertificateResponseSignatureKeyInfo.setId("Id29863828");
            _returnGetBankCertificateResponseSignature.setKeyInfo(_returnGetBankCertificateResponseSignatureKeyInfo);
            java.util.List<org.w3._2000._09.xmldsig_.ObjectType> _returnGetBankCertificateResponseSignatureObject = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ObjectType>();
            _returnGetBankCertificateResponseSignature.getObject().addAll(_returnGetBankCertificateResponseSignatureObject);
            _returnGetBankCertificateResponseSignature.setId("Id-889235367");
            _returnGetBankCertificateResponse.setSignature(_returnGetBankCertificateResponseSignature);
            _returnGetBankCertificateResponse.setId("Id-1144741010");
            _return.setGetBankCertificateResponse(_returnGetBankCertificateResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PKIFactoryServiceFault("PKIFactoryServiceFault...");
    }

    /* (non-Javadoc)
     * @see dk.danskebank.pki.pkifactoryservice.PkiServicePortType#certificateStatus(dk.danskebank.pki.pkifactoryservice.CertificateStatusInType  certificateStatusIn )*
     */
    public dk.danskebank.pki.pkifactoryservice.CertificateStatusOutType certificateStatus(CertificateStatusInType certificateStatusIn) throws PKIFactoryServiceFault    { 
        LOG.info("Executing operation certificateStatus");
        System.out.println(certificateStatusIn);
        try {
            dk.danskebank.pki.pkifactoryservice.CertificateStatusOutType _return = new dk.danskebank.pki.pkifactoryservice.CertificateStatusOutType();
            dk.danskebank.pki.pkifactoryservice.ResponseHeaderType _returnResponseHeader = new dk.danskebank.pki.pkifactoryservice.ResponseHeaderType();
            _returnResponseHeader.setSenderId("SenderId-1108180834");
            _returnResponseHeader.setCustomerId("CustomerId-1112101243");
            _returnResponseHeader.setRequestId("RequestId286038566");
            _returnResponseHeader.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.798+01:00"));
            _returnResponseHeader.setInterfaceVersion("InterfaceVersion247530219");
            dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType _returnResponseHeaderEnvironment = dk.danskebank.pki.pkifactoryservice.elements.EnvironmentType.SYSTEMTEST;
            _returnResponseHeader.setEnvironment(_returnResponseHeaderEnvironment);
            _return.setResponseHeader(_returnResponseHeader);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusResponse _returnCertificateStatusResponse = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusResponse();
            _returnCertificateStatusResponse.setReturnCode("ReturnCode-552247585");
            _returnCertificateStatusResponse.setReturnText("ReturnText801173885");
            java.util.List<dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType> _returnCertificateStatusResponseCertificateStatus = new java.util.ArrayList<dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType>();
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType _returnCertificateStatusResponseCertificateStatusVal1 = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType();
            _returnCertificateStatusResponseCertificateStatusVal1.setCertificateSerialNo("CertificateSerialNo-248767617");
            dk.danskebank.pki.pkifactoryservice.elements.CertificateTypeType _returnCertificateStatusResponseCertificateStatusVal1CertificateType = dk.danskebank.pki.pkifactoryservice.elements.CertificateTypeType.ENCRYPTION;
            _returnCertificateStatusResponseCertificateStatusVal1.setCertificateType(_returnCertificateStatusResponseCertificateStatusVal1CertificateType);
            _returnCertificateStatusResponseCertificateStatusVal1.setMatchingCertificateSerialNo("MatchingCertificateSerialNo1209101509");
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status _returnCertificateStatusResponseCertificateStatusVal1Status = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status();
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Good _returnCertificateStatusResponseCertificateStatusVal1StatusGood = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Good();
            _returnCertificateStatusResponseCertificateStatusVal1StatusGood.setExpiryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.799+01:00"));
            _returnCertificateStatusResponseCertificateStatusVal1Status.setGood(_returnCertificateStatusResponseCertificateStatusVal1StatusGood);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.ExpiresSoon _returnCertificateStatusResponseCertificateStatusVal1StatusExpiresSoon = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.ExpiresSoon();
            _returnCertificateStatusResponseCertificateStatusVal1StatusExpiresSoon.setExpiryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.800+01:00"));
            _returnCertificateStatusResponseCertificateStatusVal1Status.setExpiresSoon(_returnCertificateStatusResponseCertificateStatusVal1StatusExpiresSoon);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Expired _returnCertificateStatusResponseCertificateStatusVal1StatusExpired = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Expired();
            _returnCertificateStatusResponseCertificateStatusVal1StatusExpired.setExpiryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.800+01:00"));
            _returnCertificateStatusResponseCertificateStatusVal1Status.setExpired(_returnCertificateStatusResponseCertificateStatusVal1StatusExpired);
            dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Revoked _returnCertificateStatusResponseCertificateStatusVal1StatusRevoked = new dk.danskebank.pki.pkifactoryservice.elements.CertificateStatusType.Status.Revoked();
            _returnCertificateStatusResponseCertificateStatusVal1StatusRevoked.setRevocationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.800+01:00"));
            _returnCertificateStatusResponseCertificateStatusVal1StatusRevoked.setCRLReason(new java.math.BigInteger("-8912214027025533011116988243515459173"));
            _returnCertificateStatusResponseCertificateStatusVal1Status.setRevoked(_returnCertificateStatusResponseCertificateStatusVal1StatusRevoked);
            _returnCertificateStatusResponseCertificateStatusVal1.setStatus(_returnCertificateStatusResponseCertificateStatusVal1Status);
            _returnCertificateStatusResponseCertificateStatus.add(_returnCertificateStatusResponseCertificateStatusVal1);
            _returnCertificateStatusResponse.getCertificateStatus().addAll(_returnCertificateStatusResponseCertificateStatus);
            _returnCertificateStatusResponse.setTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-01-28T15:18:54.801+01:00"));
            _returnCertificateStatusResponse.setRequestId("RequestId-896658063");
            org.w3._2000._09.xmldsig_.SignatureType _returnCertificateStatusResponseSignature = new org.w3._2000._09.xmldsig_.SignatureType();
            org.w3._2000._09.xmldsig_.SignedInfoType _returnCertificateStatusResponseSignatureSignedInfo = new org.w3._2000._09.xmldsig_.SignedInfoType();
            org.w3._2000._09.xmldsig_.CanonicalizationMethodType _returnCertificateStatusResponseSignatureSignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig_.CanonicalizationMethodType();
            java.util.List<java.lang.Object> _returnCertificateStatusResponseSignatureSignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnCertificateStatusResponseSignatureSignedInfoCanonicalizationMethod.getContent().addAll(_returnCertificateStatusResponseSignatureSignedInfoCanonicalizationMethodContent);
            _returnCertificateStatusResponseSignatureSignedInfoCanonicalizationMethod.setAlgorithm("Algorithm-45142369");
            _returnCertificateStatusResponseSignatureSignedInfo.setCanonicalizationMethod(_returnCertificateStatusResponseSignatureSignedInfoCanonicalizationMethod);
            org.w3._2000._09.xmldsig_.SignatureMethodType _returnCertificateStatusResponseSignatureSignedInfoSignatureMethod = new org.w3._2000._09.xmldsig_.SignatureMethodType();
            java.util.List<java.lang.Object> _returnCertificateStatusResponseSignatureSignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
            _returnCertificateStatusResponseSignatureSignedInfoSignatureMethod.getContent().addAll(_returnCertificateStatusResponseSignatureSignedInfoSignatureMethodContent);
            _returnCertificateStatusResponseSignatureSignedInfoSignatureMethod.setAlgorithm("Algorithm445622794");
            _returnCertificateStatusResponseSignatureSignedInfo.setSignatureMethod(_returnCertificateStatusResponseSignatureSignedInfoSignatureMethod);
            java.util.List<org.w3._2000._09.xmldsig_.ReferenceType> _returnCertificateStatusResponseSignatureSignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ReferenceType>();
            _returnCertificateStatusResponseSignatureSignedInfo.getReference().addAll(_returnCertificateStatusResponseSignatureSignedInfoReference);
            _returnCertificateStatusResponseSignatureSignedInfo.setId("Id-693254675");
            _returnCertificateStatusResponseSignature.setSignedInfo(_returnCertificateStatusResponseSignatureSignedInfo);
            org.w3._2000._09.xmldsig_.SignatureValueType _returnCertificateStatusResponseSignatureSignatureValue = new org.w3._2000._09.xmldsig_.SignatureValueType();
            byte[] _returnCertificateStatusResponseSignatureSignatureValueValue = new byte[] {};
            _returnCertificateStatusResponseSignatureSignatureValue.setValue(_returnCertificateStatusResponseSignatureSignatureValueValue);
            _returnCertificateStatusResponseSignatureSignatureValue.setId("Id-627955397");
            _returnCertificateStatusResponseSignature.setSignatureValue(_returnCertificateStatusResponseSignatureSignatureValue);
            org.w3._2000._09.xmldsig_.KeyInfoType _returnCertificateStatusResponseSignatureKeyInfo = new org.w3._2000._09.xmldsig_.KeyInfoType();
            java.util.List<java.lang.Object> _returnCertificateStatusResponseSignatureKeyInfoContent = new java.util.ArrayList<java.lang.Object>();
            _returnCertificateStatusResponseSignatureKeyInfo.getContent().addAll(_returnCertificateStatusResponseSignatureKeyInfoContent);
            _returnCertificateStatusResponseSignatureKeyInfo.setId("Id-1698910277");
            _returnCertificateStatusResponseSignature.setKeyInfo(_returnCertificateStatusResponseSignatureKeyInfo);
            java.util.List<org.w3._2000._09.xmldsig_.ObjectType> _returnCertificateStatusResponseSignatureObject = new java.util.ArrayList<org.w3._2000._09.xmldsig_.ObjectType>();
            _returnCertificateStatusResponseSignature.getObject().addAll(_returnCertificateStatusResponseSignatureObject);
            _returnCertificateStatusResponseSignature.setId("Id-1076182754");
            _returnCertificateStatusResponse.setSignature(_returnCertificateStatusResponseSignature);
            _returnCertificateStatusResponse.setId("Id1664013710");
            _return.setCertificateStatusResponse(_returnCertificateStatusResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PKIFactoryServiceFault("PKIFactoryServiceFault...");
    }

}
