//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.SoapLibrary.Specification.CaptureV02
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.danskebank.com/services/",
        ConfigurationName = "CaptureV02")]
    public interface CaptureV02
    {

        // CODEGEN: Generating message contract since message CaptureRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CaptureResponse Capture(CaptureRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<CaptureResponse> CaptureAsync(CaptureRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
                    "")]
    public partial class SecurityHeaderType
    {

        private System.Xml.XmlElement[] anyField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlElement[] Any
        {
            get { return this.anyField; }
            set { this.anyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get { return this.anyAttrField; }
            set { this.anyAttrField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.danskebank.com/SecureSoapSGW")]
    public partial class RequestHeaderType
    {

        private string senderIdField;

        private string signerId1Field;

        private string signerId2Field;

        private string signerId3Field;

        private string dBCryptIdField;

        private string requestIdField;

        private string timestampField;

        private string languageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SenderId
        {
            get { return this.senderIdField; }
            set { this.senderIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string SignerId1
        {
            get { return this.signerId1Field; }
            set { this.signerId1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string SignerId2
        {
            get { return this.signerId2Field; }
            set { this.signerId2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string SignerId3
        {
            get { return this.signerId3Field; }
            set { this.signerId3Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string DBCryptId
        {
            get { return this.dBCryptIdField; }
            set { this.dBCryptIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string RequestId
        {
            get { return this.requestIdField; }
            set { this.requestIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Timestamp
        {
            get { return this.timestampField; }
            set { this.timestampField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string Language
        {
            get { return this.languageField; }
            set { this.languageField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.danskebank.com/services/")]
    public partial class Output
    {

        private string reasonCodeField;

        private string originalTransactionIdField;

        private decimal remainderAmountField;

        private string returnCodeField;

        private string transactionIdField;

        public Output()
        {
            this.remainderAmountField = ((decimal) (0.0m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ReasonCode
        {
            get { return this.reasonCodeField; }
            set { this.reasonCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OriginalTransactionId
        {
            get { return this.originalTransactionIdField; }
            set { this.originalTransactionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal RemainderAmount
        {
            get { return this.remainderAmountField; }
            set { this.remainderAmountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string ReturnCode
        {
            get { return this.returnCodeField; }
            set { this.returnCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string TransactionId
        {
            get { return this.transactionIdField; }
            set { this.transactionIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.danskebank.com/services/")]
    public partial class Input
    {

        private string bulkRefField;

        private string dateFromField;

        private string dateToField;

        private string transactionIdField;

        private decimal amountField;

        private string merchantIdField;

        private string orderIdField;

        private string testField;

        public Input()
        {
            this.amountField = ((decimal) (0.0m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BulkRef
        {
            get { return this.bulkRefField; }
            set { this.bulkRefField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string DateFrom
        {
            get { return this.dateFromField; }
            set { this.dateFromField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string DateTo
        {
            get { return this.dateToField; }
            set { this.dateToField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string TransactionId
        {
            get { return this.transactionIdField; }
            set { this.transactionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal Amount
        {
            get { return this.amountField; }
            set { this.amountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string MerchantId
        {
            get { return this.merchantIdField; }
            set { this.merchantIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string OrderId
        {
            get { return this.orderIdField; }
            set { this.orderIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string Test
        {
            get { return this.testField; }
            set { this.testField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "Capture",
        WrapperNamespace = "http://www.danskebank.com/services/", IsWrapped = true)]
    public partial class CaptureRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(
            Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
                        "")] public SecurityHeaderType Security;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.danskebank.com/SecureSoapSGW")] public
            RequestHeaderType RequestHeader;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.danskebank.com/services/", Order = 0)] public Input Input;

        public CaptureRequest()
        {
        }

        public CaptureRequest(SecurityHeaderType Security, RequestHeaderType RequestHeader, Input Input)
        {
            this.Security = Security;
            this.RequestHeader = RequestHeader;
            this.Input = Input;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CaptureResponse",
        WrapperNamespace = "http://www.danskebank.com/services/", IsWrapped = true)]
    public partial class CaptureResponse
    {

        [System.ServiceModel.MessageHeaderAttribute(
            Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
                        "")] public SecurityHeaderType Security;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.danskebank.com/services/", Order = 0)] public Output Output;

        public CaptureResponse()
        {
        }

        public CaptureResponse(SecurityHeaderType Security, Output Output)
        {
            this.Security = Security;
            this.Output = Output;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CaptureV02Channel : CaptureV02, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaptureV02Client : System.ServiceModel.ClientBase<CaptureV02>, CaptureV02
    {

        public CaptureV02Client()
        {
        }

        public CaptureV02Client(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CaptureV02Client(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CaptureV02Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CaptureV02Client(System.ServiceModel.Channels.Binding binding,
            System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CaptureResponse CaptureV02.Capture(CaptureRequest request)
        {
            return base.Channel.Capture(request);
        }

        public Output Capture(ref SecurityHeaderType Security, RequestHeaderType RequestHeader, Input Input)
        {
            CaptureRequest inValue = new CaptureRequest();
            inValue.Security = Security;
            inValue.RequestHeader = RequestHeader;
            inValue.Input = Input;
            CaptureResponse retVal = ((CaptureV02) (this)).Capture(inValue);
            Security = retVal.Security;
            return retVal.Output;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CaptureResponse> CaptureV02.CaptureAsync(CaptureRequest request)
        {
            return base.Channel.CaptureAsync(request);
        }

        public System.Threading.Tasks.Task<CaptureResponse> CaptureAsync(SecurityHeaderType Security,
            RequestHeaderType RequestHeader, Input Input)
        {
            CaptureRequest inValue = new CaptureRequest();
            inValue.Security = Security;
            inValue.RequestHeader = RequestHeader;
            inValue.Input = Input;
            return ((CaptureV02) (this)).CaptureAsync(inValue);
        }
    }
}